Traceback (most recent call last):
  File "/home/martinsummer/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/martinsummer/.local/lib/python3.10/site-packages/nbclient/client.py", line 1269, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/martinsummer/.local/lib/python3.10/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/martinsummer/.local/lib/python3.10/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/martinsummer/.local/lib/python3.10/site-packages/nbclient/client.py", line 707, in async_execute
    await self.async_execute_cell(
  File "/home/martinsummer/.local/lib/python3.10/site-packages/nbclient/client.py", line 1025, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/martinsummer/.local/lib/python3.10/site-packages/nbclient/client.py", line 919, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
Austria is between the US and Japan and tends towards a top layered country.
------------------

Error in parse(text = x, srcfile = src): <text>:1:9: unexpected symbol
1: Austria is
            ^
Traceback:

ERROR: Error in parse(text = x, srcfile = src): <text>:1:9: unexpected symbol
1: Austria is
            ^


